name: Workflows

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Shellcheck Version Check
        run: shellcheck -V
      - name: Run ShellCheck
        run: shellcheck mkRAMDisk.sh

  mount-and-test:
    runs-on: macos-14
    steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Goss downloaded cache
          uses: actions/cache/restore@v4
          with:
            path: /tmp/goss
            key: mkramdisk-goss

        - name: Download Goss
          run: |
            curl -L https://github.com/goss-org/goss/releases/download/v0.4.6/goss-darwin-arm64 \
                -o /tmp/goss && \
            chmod +x /tmp/goss

        - name: Store goss cache
          uses: actions/cache/save@v4
          with:
            path: /tmp/goss
            key: mkramdisk-goss

        - name: Run mkRAMDisk.sh
          run: |
            ./mkRAMDisk.sh

        - name: Run goss (mkRAMDisk.sh)
          run: |
            /tmp/goss -g goss_mount.yaml validate
          env:
            GOSS_USE_ALPHA: 1

        - name: Run ejectRAMDisk.sh
          run: |
            mount && \
            ls /Volumes && \
            ./ejectRAMDisk.sh

        - name: Run goss (ejectRAMDisk.sh)
          run: |
            /tmp/goss -g goss_eject.yaml validate
          env:
            GOSS_USE_ALPHA: 1
