name: shellcheck

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: which
        run: which shellcheck
      - name: Shellcheck Version Check
        run: shellcheck -V
      - name: Where am i
        run: pwd
      - name: ls
        run: ls
      - name: Run ShellCheck
        run: shellcheck mkRAMDisk.sh

